[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Elementa"
authors = [{name = "Lirry", email = "l.pinter@elementalabs.com"}]
dynamic = ["version", "description"]
